// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Accordion from './Accordion/index.svelte';
import BlogPost from './BlogPost/index.svelte';
import ContentIndex from './ContentIndex/index.svelte';
import LogoSlider from './LogoSlider/index.svelte';
import Grid from './Grid/index.svelte';
import Hero from './Hero/index.svelte';
import HeroVideo from './HeroVideo/index.svelte';
import ManufacturersSlider from './ManufacturersSlider/index.svelte';
import PressLoop from './PressLoop/index.svelte';
import RichText from './RichText/index.svelte';
import Services from './Services/index.svelte';
import Testimonials from './Testimonials/index.svelte';

export const components = {
	about: About,
	accordion: Accordion,
	blog_post: BlogPost,
	content_index: ContentIndex,
	customer_logos: LogoSlider,
	grid: Grid,
	hero: Hero,
	hero_video: HeroVideo,
	manufacturers_slider: ManufacturersSlider,
	press_loop: PressLoop,
	rich_text: RichText,
	services: Services,
	testimonials: Testimonials
};
